cart/urls.py
from django.conf.urls.static import static
from django.urls import path
from ecommerce1 import settings
from . import views

urlpatterns = [
	path("", views.view, name="cart"),
	path("<slug>/", views.update_cart, name="update-cart"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ecommerce1 import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include("product.urls")),
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
    path('cart/', include("cart.urls")),
    path('order/', include("order.urls")),
    path('accounts/', include("account.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.
from product.models import Product

class Item(models.Model):
	cart = models.ForeignKey('Cart', null=True, blank=True, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)

	quantity = models.IntegerField(default=1)
	item_total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.product.title


class Cart(models.Model):
	# items = models.ManyToManyField(CartItem, null=True, blank=True)
	cart_total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		return "Cart id: %s" % self.id

product/models.py
from django.db import models

class Product(models.Model):
	title = models.CharField(max_length=120, null=False, blank=False)
	description = models.TextField(null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=29.99)
	sale_price = models.DecimalField(max_digits=100, decimal_places=2, default=29.99, null=True, blank=True)
	slug = models.SlugField(unique=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.title

	def get_price(self):
		return self.price


class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	image = models.ImageField(blank=True, upload_to="products/images/")
	featured = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)
	thumbnail = models.BooleanField(default=False)

	def __str__(self):
		return self.product.title + " " + str(self.id)

cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from product.models import Product
from .models import Cart, Item


# Create your views here.

def view(request):
	"""
	Viewing the cart process:

	1.user session checking and getting the cart, send it as context (old session)
	2. if not get, send no cart(new session)
	"""

	template = "cart/view.html"
	try:
		cart_id = request.session["cart_id"]
	except KeyError:
		cart_id = None

	if cart_id:
		cart = Cart.objects.get(id=cart_id)
		context = {
			"cart": cart
		}
	else:
		context = {
			"cart": None
		}

	return render(request, template, context)


def update_cart(request, slug):
	"""
	Rule - One cart per session, multiple items per cart, single product + multiple quantity per item

	when adding/removing any product to the cart, it has to do this things:
	A. user session checking and getting the cart or creating it
	1. checks who is the user and if he has a cart for his current session
	2. if the user has a cart in his running session (old session) get his cart by
		his cart_id from his running session
	3. if the user has no cart in his session(new session), create a cart, save it and store the cart in the current
		session for	further use

	B. adding/removing product
	1. get the product using the provided slug
	2. if the product is in any of the cart_item's product list, get it, if not, create it as cart item.
	3. then we get the product as cart item by getting it or creating it
	4. if this cart item is not present in the cart's items list(created), add the item to the current cart's item list
	5. it it presents(get), remove it

	C. Calculating the total price for the current cart and total items in the current cart
	1. each item in the cart's item list has single product, single price but with multiple quantity
	2. so, by looping through all the items in the product, we can calculate the total price by summing each of the
		product's price multiplied by quantity.
		So total price(cart) = sum(each_cart_item_product_price * product_quantity)
	3. save the total price for the cart
	4. calculating items quantity by counting all the items in the cart, since each item contain single product
	5. saving the items quanitity in the current session for future use
	"""

	try:
		cart_id = request.session["cart_id"]
		cart = Cart.objects.get(id=cart_id)
	except:
		cart = Cart.objects.create()
		cart.save()
		request.session["cart_id"] = cart.id

	product = Product.objects.get(slug=slug)
	try:
		qty = request.GET.get("qty")
	except:
		qty = None

	try:
		cart_item = Item.objects.get(product=product, cart=cart)

	except:
		cart_item = None

	if qty != '0' and not cart_item:
		Item.objects.create(product=product, cart=cart, quantity=qty)
	elif cart_item and qty == '0':
		cart_item.delete()
	else:
		cart_item.quantity = qty
		cart_item.save()

	cart.cart_total = 0.00
	for item in cart.item_set.all():
		item.item_total = float(item.product.sale_price) * item.quantity
		item.save()
		cart.cart_total += item.item_total
		cart.save()

	request.session["total_price"] = cart.cart_total
	request.session["total_items"] = cart.item_set.count()
	cart.save()
	return HttpResponseRedirect(reverse("cart"))

cart/templates/cart/view.html
{% extends 'product/base.html' %}
{% load static %}
{% block title %}
    Pikom | Products
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                {% if not cart.item_set.all %}
                    <div class="panel-heading">Your cart is empty. Please make some shopping</div>
                {% else %}
                    <div class="panel-heading">Your cart</div>
                {% endif %}
                <div class="panel-body">
                    {% if cart.item_set.all %}
                        <table class="table table-striped table-bordered table-condensed" id="cart_table">
                            <thead>
                                <tr>
                                    <th align="center">Sl.</th>
                                    <th align="center">Preview</th>
                                    <th align="center">Item name</th>
                                    <th align="center">Price</th>
                                    <th align="center">Quantity</th>
                                    <th align="center">Item Price</th>
                                    <th align="center">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart.item_set.all %}
                                    <td>{{ forloop.counter }}</td>
                                    <td> {% for image in item.product.productimage_set.all %}
                                        {% if image.thumbnail %}
                                            <img src="{{ image.image.url }}" height="30">
                                        {% endif %}
                                    {% endfor %}</td>
                                    <td>{{ item.product.title }}</td>
                                    <td>{{ item.product.sale_price }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.item_total }}</td>
                                    <td colspan="1">
                                        <a href="{% url 'update-cart' item.product.slug %}?qty=0"><i
                                                class="fa fa-trash-o fa-2x" aria-hidden="true"></i></a></td>
                                    </tr>
                                {% endfor %}

                                <tr class="tr">
                                    <td colspan="3"><a href="{% url 'home' %}" class="btn btn-success">Continue
                                                                                                       shopping</a></td>
                                    <td colspan="2"></td>
                                    <td>
                                        <p style="font-weight: bold">Total: {{ cart.cart_total }}</p>
                                    </td>
                                    <td><a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a></td>
                                </tr>
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'calc.js' %}"></script>
{% endblock %}